name: fintech_folio
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.0.2
  firebase_database: ^6.1.1
  firebase_auth: ^1.0.1
  modal_progress_hud: ^0.1.3
  http: ^0.13.1 # https://pub.dev/packages/http
  cached_network_image: ^2.0.0
  webview_flutter: ^0.3.19+9


  cupertino_icons: ^1.0.0
  dropdown_formfield: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  syncfusion_flutter_charts: ^18.4.49


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/icons/
     - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Nunito
       fonts:
         - asset: fonts/Nunito-Regular.ttf
         - asset: fonts/Nunito-Italic.ttf
           style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
